### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ezbooz** [EricZhu-42/POE-Stash-Coffin-Manager#1]
`
C:\Users\Home\Desktop\POE-Stash-Coffin-Manager-main>main.py
Unparsed mod: Item is Corrupted
Unparsed mod: Corpses in adjacent Graves and this Corpse have their crafting outcomes randomised when this Corpse is buried
Unparsed mod: Creates a Cerulean Ring
Unparsed mod: Reforge socket numbers 200 times, keeping the greatest number of sockets
Unparsed mod: Reforge socket links 200 times, keeping the greatest number of links
Unparsed mod: Item sells for much more to Vendors
Unparsed mod: Armour can roll Haunted Modifiers
Traceback (most recent call last):
  File "C:\Users\Home\Desktop\POE-Stash-Coffin-Manager-main\main.py", line 59, in <module>
    main()
  File "C:\Users\Home\Desktop\POE-Stash-Coffin-Manager-main\main.py", line 19, in main
    data = coffin_parser.parse_coffin(coffins, verbose=VERBOSE)
  File "C:\Users\Home\Desktop\POE-Stash-Coffin-Manager-main\coffin_parser.py", line 49, in parse_coffin
    data[mode_type][imp]["sub_counts"][cat] += 1
KeyError: 'Eldritch'

C:\Users\Home\Desktop\POE-Stash-Coffin-Manager-main>`

**Comment by Xp-speit2018** [comment]
Hi, could you provide which coffin is causing the error? You can use regex filter "Eldritch" in your stash and hover over the highlighted item then press "Ctrl + C" to copy the item.

**Comment by ezbooz** [comment]
> Hi, could you provide which coffin is causing the error? You can use regex filter "Eldritch" in your stash and hover over the highlighted item then press "Ctrl + C" to copy the item.

all haunted, reforge socket numbers and links



```
Item Class: Stackable Currency
Rarity: Currency
Filled Coffin
--------
Monster: Flame Hellion
Corpse Level: 83
Monster Category: Beast
--------
Item is Corrupted (implicit)
50% increased chance for Corruption Implicit Modifiers (implicit)
--------
Right click on this item to use it while in the Necropolis to add it to the Necropolis Morgue.

Item Class: Stackable Currency
Rarity: Currency
Filled Coffin
--------
Monster: Spine Serpent
Corpse Level: 83
Monster Category: Construct
--------
Reforge socket links 200 times, keeping the greatest number of links (implicit)
--------
Right click on this item to use it while in the Necropolis to add it to the Necropolis Morgue.

Item Class: Stackable Currency
Rarity: Currency
Filled Coffin
--------
Monster: Depraved Enforcer
Corpse Level: 83
Monster Category: Humanoid
--------
Item sells for much more to Vendors (implicit)
Requires at least 2 other Corpses of the same Monster Name (implicit)
--------
Right click on this item to use it while in the Necropolis to add it to the Necropolis Morgue.

```

**Comment by Xp-speit2018** [comment]
It seems that we've missed corpse typed "Eldrich". Patch coming soon

**Comment by EricZhu-42** [comment]
Hi @ezbooz,

Thanks for bringing this to our attention! 

Now coffins with `Eldritch` category can be successfully parsed, see 24776b523b1d2ff8022236001a2fec45ada1ef8d.
